# Generated by Django 4.1.4 on 2023-05-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailableLabel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_title", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DemandTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_title", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlantScienceTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_title", models.CharField(blank=True, max_length=500, null=True)),
                ("tag_value", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="media/products")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("sub_title", models.CharField(blank=True, max_length=1000, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "cannabinoids",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("aroma", models.CharField(blank=True, max_length=1000, null=True)),
                ("terpenes", models.CharField(blank=True, max_length=1000, null=True)),
                ("origin", models.CharField(blank=True, max_length=500, null=True)),
                ("plant_science_description", models.TextField()),
                (
                    "available_in_tags",
                    models.ManyToManyField(to="product.availablelabel"),
                ),
                (
                    "plant_science_tags",
                    models.ManyToManyField(to="product.plantsciencetag"),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productcategory",
                    ),
                ),
                (
                    "product_main_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productimage",
                    ),
                ),
                (
                    "product_more_image",
                    models.ManyToManyField(
                        related_name="product_more_image", to="product.productimage"
                    ),
                ),
                ("top_trending_tags", models.ManyToManyField(to="product.demandtag")),
            ],
        ),
    ]
