# Generated by Django 4.1.4 on 2023-04-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailableLabel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_title", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DemandTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_title", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlantScienceTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_title", models.CharField(blank=True, max_length=500, null=True)),
                ("tag_value", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("sub_title", models.CharField(blank=True, max_length=1000, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "cannabinoids",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("aroma", models.CharField(blank=True, max_length=1000, null=True)),
                ("terpenes", models.CharField(blank=True, max_length=1000, null=True)),
                ("origin", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "product_state",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Upcoming", "Upcoming"),
                            ("Unavailable", "Unavailable"),
                        ],
                        max_length=100,
                    ),
                ),
                ("plant_science_description", models.TextField()),
                (
                    "available_in_tags",
                    models.ManyToManyField(to="product.availablelabel"),
                ),
                (
                    "plant_science_tags",
                    models.ManyToManyField(to="product.plantsciencetag"),
                ),
                ("top_trending_tags", models.ManyToManyField(to="product.demandtag")),
            ],
        ),
    ]
