# Generated by Django 4.1.4 on 2023-04-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="media/products")),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_state",
        ),
        migrations.AddField(
            model_name="product",
            name="product_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productimage",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_more_image",
            field=models.ManyToManyField(
                related_name="product_more_image", to="product.productimage"
            ),
        ),
    ]
