# Generated by Django 4.1.4 on 2023-05-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalregister",
            name="responsible_gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "male"), ("female", "female"), ("other", "other")],
                max_length=20,
                null=True,
            ),
        ),
    ]
