# Generated by Django 4.1.4 on 2023-04-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactqueries",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
