# Generated by Django 4.1.4 on 2023-04-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_User", "0002_contactqueries_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
