# Generated by Django 4.1.4 on 2023-05-06 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App_User", "0003_basemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisistorLogs",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="App_User.basemodel",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("age", models.IntegerField()),
                ("uuid", models.UUIDField()),
                ("request_browser", models.CharField(max_length=1000)),
            ],
            bases=("App_User.basemodel",),
        ),
    ]
